###################################################################################
# Purpose       :   Clone and modify proxmox templates for MAS 3.2
# Author        :   DGS
# Date          :   24.03.2024
# Version       :   3.5
###################################################################################
---
- hosts: proxmox
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
  - name: Clone VM Server with only source VM name - Linked Clone
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      clone: "{{ clone_name_srv }}" # The VM source
      name: "{{ new_srv_name }}"  # The target VM name
      node: "{{ node }}"
      full: no
  - name: Clone VM Client with only source VM name - Linked Clone
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      clone: "{{ clone_name_cli }}" # The VM source
      name: "{{ new_cli_name }}"  # The target VM name
      node: "{{ node }}"
      full: no
  - name: Clone VM Server App with only source VM name - Linked Clone
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      clone: "{{ clone_app_srv }}" # The VM source
      name: "{{ new_app_srv }}"  # The target VM name
      node: "{{ node }}"
      full: no
    when: srvapp_var is match("true")
  - name: Pause for 2 minutes to wait the VM Start
    ansible.builtin.pause:
      minutes: 5
  - name: Start VM Server
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host    : "{{ api_host }}"
      name        : "{{ new_srv_name }}"
      node        : "{{ node }}"
      state       : started
  - name: Start VM Client
    community.general.proxmox_kvm:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host    : "{{ api_host }}"
      name        : "{{ new_cli_name }}"
      node        : "{{ node }}"
      state       : started
  - name: Wait for Proxmox VMs to respond to SSH
    ansible.builtin.wait_for:
      host: "{{ item }}"
      port: 22
      delay: 30
      timeout: 500
      state: started
    retries: 30
    delay: 10
    delegate_to: localhost
    loop:
      - "{{ip_loop}}"
      - "{{ip_loop_2}}"
- hosts: wserver
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
  - name: Change the hostname to DC1
    ansible.windows.win_hostname:
      name: "{{ dc_hostname }}"
  - name: Reboot the machine with all defaults
    ansible.windows.win_reboot:
  - name: Wait for Proxmox VMs to respond to SSH
    ansible.builtin.wait_for:
      host: "{{ item }}"
      port: 22
      delay: 10
      timeout: 500
      state: started
    retries: 30
    delay: 10
    delegate_to: localhost
    loop:
      - "{{ ip_loop }}"
  - name: Create Domain
    ansible.windows.win_domain: >
      dns_domain_name="{{ domain_name }}"
      safe_mode_password="{{ recovery_password }}"
  - name: Config DHCP with Powershell
    ansible.windows.win_powershell:
      script: |
        Add-DhcpServerv4Scope -name "MAS32" -StartRange 10.0.0.1 -EndRange 10.0.0.254 -SubnetMask 255.255.255.0 -State Active
        Add-DhcpServerv4ExclusionRange -ScopeID 10.0.0.0 -StartRange 10.0.0.1 -EndRange 10.0.0.15
        Set-DhcpServerv4OptionValue -OptionID 3 -Value 10.0.0.1 -ScopeID 10.0.0.0 -ComputerName SRV-DC1
        Set-DhcpServerv4OptionValue -DnsDomain pipo.miel -DnsServer 10.0.0.12
        Start-Sleep -Seconds 10
  - name: Reboot the machine with all defaults
    ansible.windows.win_reboot:

#### EXECUTION : ansible-playbook -i inventory.cfg -i inventory2.cfg master.yaml

