###################################################################################
# Purpose       :   Configure DHCP as Admin User for MAS 3.2
# Author        :   DGS
# Date          :   24.03.2024
# Version       :   1.0
###################################################################################
---
- hosts: wserverdhcp
  gather_facts: no
  vars_files:
    - vars.yaml
  tasks:
  - name: Install DHCP with Powershell
    ansible.windows.win_powershell:
      script: |
        $Username = 'pipo.miel\Administrateur'
        $Password = ConvertTo-SecureString 'Pa$$w0rd' -AsPlainText -Force
        $Credential = New-Object System.Management.Automation.PSCredential($Username, $Password)

        Invoke-Command -ComputerName SRV-DC1 -Credential $Credential -ScriptBlock {
            Add-DhcpServerInDC -DnsName SRV-DC1.pipo.miel -IPAddress 10.0.0.12
        }
  - name: Reboot the machine with all defaults
    ansible.windows.win_reboot:

